[green_agent]
agentbeats_id = "019bc152-03ee-7081-a67d-fd979c2b7d94" # Set your Green Agent ID from agentbeats.dev
image = "ghcr.io/ychuang2112sub/reasearch-slide-quality-auditor-a2a-green-agent:main"
env = { GEMINI_API_KEY = "${GEMINI_API_KEY}" }

[[participants]]
agentbeats_id = "" # Set participant ID
name = "agent"
image = ""
env = {}

[config]
domain = "research-audit"
num_tasks = 1
research_data = {
    query = "The Future of Agentic AI"
}